// 
// Generated by @himenon/openapi-typescript-code-generator v1.0.11
// 
// OpenApi : 3.1.0
// 
// 


export namespace Schemas {
    export interface CreateInquiryRequestSchema {
        /**
         * メールアドレス
         *
         * 問い合わせ者のメールアドレス
         */
        email: string;
        /**
         * 名
         *
         * 問い合わせ者の名
         */
        firstName: string | null;
        /**
         * 姓
         *
         * 問い合わせ者の姓
         */
        familyName: string | null;
        /**
         * カテゴリー
         *
         * 問い合わせのカテゴリー
         */
        category: string | null;
        /**
         * 件名
         *
         * 問い合わせの件名
         */
        subject: string | null;
        /**
         * 本文
         *
         * 問い合わせの本文
         */
        content: string;
        /**
         * 所属
         *
         * 問い合わせ者の所属
         */
        affiliation: string | null;
        /**
         * 電話番号
         *
         * 問い合わせ者の電話番号
         */
        phoneNumber: string | null;
    }
    export interface EntryCreateRequestSchema {
        /**
         * メールアドレス
         *
         * エントリー者のメールアドレス
         */
        email: string;
        /**
         * 姓
         *
         * エントリー者の姓
         */
        familyName: string | null;
        /**
         * 名
         *
         * エントリー者の名
         */
        firstName: string | null;
        /**
         * 住所
         *
         * エントリー者の住所
         */
        address: string | null;
        /**
         * 雇用形態
         *
         * エントリー者の雇用形態
         */
        employmentType: string | null;
        /**
         * 最寄り駅
         *
         * エントリー者の最寄り駅
         */
        nearestStation: string | null;
        /**
         * 当社を知ったサイト
         *
         * 当社を知るきっかけになったサイト
         */
        websiteToLearnAboutUs: string | null;
        /**
         * 勤務時間
         *
         * エントリー者の勤務時間
         */
        workingTime: string | null;
        /**
         * その他
         *
         * その他の情報
         */
        other: string | null;
    }
    export interface EntrySchema {
        /**
         * ID
         *
         * エントリーのID
         */
        id: string;
        /**
         * 作成日時
         *
         * データが作成された日時
         */
        createdAt: string;
        /**
         * 更新日時
         *
         * データが更新された日時
         */
        updatedAt: string;
        /**
         * メールアドレス
         *
         * エントリー者のメールアドレス
         */
        email: string;
        /**
         * 姓
         *
         * エントリー者の姓
         */
        familyName: string | null;
        /**
         * 名
         *
         * エントリー者の名
         */
        firstName: string | null;
        /**
         * 住所
         *
         * エントリー者の住所
         */
        address: string | null;
        /**
         * 雇用形態
         *
         * エントリー者の雇用形態
         */
        employmentType: string | null;
        /**
         * 最寄り駅
         *
         * エントリー者の最寄り駅
         */
        nearestStation: string | null;
        /**
         * 当社を知ったサイト
         *
         * 当社を知るきっかけになったサイト
         */
        websiteToLearnAboutUs: string | null;
        /**
         * 勤務時間
         *
         * エントリー者の勤務時間
         */
        workingTime: string | null;
        /**
         * その他
         *
         * その他の情報
         */
        other: string | null;
    }
    export interface HTTPValidationError {
        /** Detail */
        detail?: Schemas.ValidationError[];
    }
    export interface HealthCheckSchema {
        /**
         * ステータス
         *
         * Health Check Status
         */
        status: string;
        /**
         * APIバージョン情報
         *
         * API Version
         */
        version: string;
    }
    export interface InquiryResponseSchema {
        /**
         * ID
         *
         * 問い合わせ者のID
         */
        id: string;
        /**
         * 作成日時
         *
         * データが作成された日時
         */
        createdAt: string;
        /**
         * 更新日時
         *
         * データが更新された日時
         */
        updatedAt: string;
        /**
         * メールアドレス
         *
         * 問い合わせ者のメールアドレス
         */
        email: string;
        /**
         * 名
         *
         * 問い合わせ者の名
         */
        firstName: string | null;
        /**
         * 姓
         *
         * 問い合わせ者の姓
         */
        familyName: string | null;
        /**
         * カテゴリー
         *
         * 問い合わせのカテゴリー
         */
        category: string | null;
        /**
         * 件名
         *
         * 問い合わせの件名
         */
        subject: string | null;
        /**
         * 本文
         *
         * 問い合わせの本文
         */
        content: string;
        /**
         * 所属
         *
         * 問い合わせ者の所属
         */
        affiliation: string | null;
        /**
         * 電話番号
         *
         * 問い合わせ者の電話番号
         */
        phoneNumber: string | null;
        /**
         * 確認フラグ
         *
         * 確認したかどうかのフラグ
         */
        isChecked: boolean;
        /**
         * 重要フラグ
         *
         * 重要かどうかのフラグ
         */
        isImportant: boolean;
    }
    export interface ValidationError {
        /** Location */
        loc: (string | number)[];
        /** Error Type */
        type: string;
    }
}
